version: '3.9'

services:
  postgres_notes:
    image: postgres:latest
    container_name: db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - notes_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    command: psql -U postgresql -d notesdb -tc "SELECT 1 FROM pg_database WHERE datname = 'testdb'" | grep -q 1 || psql -U postgresql -d notesdb -c "CREATE DATABASE testdb"

volumes:
  notes_postgres_data: