version: '3.9'

services:
  postgres_notes:
    image: postgres:latest
    container_name: db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - notes_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  notes_postgres_data: